In [1]:
def findPrime(x):
    prime=[2, 3] #
    notPrime=[]
    numbers=[2,3]
    exclude=4 #done to exclude 0 and 1 as they are unique numbers, exclude 2 and 3 as to get the list started.
    for i in range(x-exclude+1):
        num=i+exclude
        status=True
        
        for j in prime:
            if num%j==0:
                status=False
        numbers.append(num)
        if status:
            prime.append(num)
        else:
            notPrime.append(num)
    return(prime, notPrime, numbers)

number=10000
prime, notPrime,numbers=findPrime(number)
#print(prime, notPrime)

        

In [2]:
import numpy as np

label=np.zeros((number-1,1))
print(label)

[[ 0.]
 [ 0.]
 [ 0.]
 ..., 
 [ 0.]
 [ 0.]
 [ 0.]]


In [3]:
for i in prime:
    label[i-2]=1
#print(label)

from keras.utils import np_utils
label_final = np_utils.to_categorical(np.array(label), 2)
print(label)
print(label_final)

Using TensorFlow backend.


[[ 1.]
 [ 1.]
 [ 0.]
 ..., 
 [ 0.]
 [ 0.]
 [ 0.]]
[[ 0.  1.]
 [ 0.  1.]
 [ 1.  0.]
 ..., 
 [ 1.  0.]
 [ 1.  0.]
 [ 1.  0.]]


In [26]:
data=np.zeros((number-1,len(str(number))))
for i in range(number-1):
    num=i+2
    for k in range(len(str(num))):
        data[i][len(str(number))-k-1]=int(str(num)[len(str(num))-k-1])
#print(data)
#data_final = np_utils.to_categorical(np.array(data), number+1)
print(data)

[[ 0.  0.  0.  0.  2.]
 [ 0.  0.  0.  0.  3.]
 [ 0.  0.  0.  0.  4.]
 ..., 
 [ 0.  9.  9.  9.  8.]
 [ 0.  9.  9.  9.  9.]
 [ 1.  0.  0.  0.  0.]]


In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, label_final, test_size=0.2, random_state=42)

In [425]:
from sklearn.ensemble import AdaBoostClassifier








In [55]:
#neural network(s):
from keras.layers import Conv1D, MaxPooling1D, GlobalAveragePooling1D, AveragePooling1D
from keras.layers import Dropout, Flatten, Dense
from keras.models import Sequential

print(X_train.shape[1])

Prime_model = Sequential()
Prime_model.add(Dense(512, input_shape=(X_train.shape[1],)))
Prime_model.add(Dropout(.3))
Prime_model.add(Dense(1024, activation='relu'))
Prime_model.add(Dropout(.3))
Prime_model.add(Dense(2048, activation='relu'))
Prime_model.add(Dropout(.3))
Prime_model.add(Dense(1024, activation='relu'))
Prime_model.add(Dropout(.3))
Prime_model.add(Dense(512, activation='relu'))
Prime_model.add(Dropout(.3))
#Prime_model.add(Dense(256, activation='relu'))
#Prime_model.add(Dropout(.3))
#Prime_model.add(Dense(128, activation='relu'))
#Prime_model.add(Dropout(.3))
#Prime_model.add(Dense(64, activation='relu'))
#Prime_model.add(Dropout(.3))
#Prime_model.add(Dense(32, activation='relu'))
#Prime_model.add(Dropout(.3))
#Prime_model.add(Dense(16, activation='relu'))
#Prime_model.add(Dropout(.3))
#Prime_model.add(Dense(8, activation='relu'))
#Prime_model.add(Dropout(.3))
#Prime_model.add(Dense(4, activation='relu'))
#Prime_model.add(Dropout(.3))
Prime_model.add(Dense(2, activation='softmax'))
Prime_model.summary()

5
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 512)               3072      
_________________________________________________________________
dropout_6 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_8 (Dense)              (None, 1024)              525312    
_________________________________________________________________
dropout_7 (Dropout)          (None, 1024)              0         
_________________________________________________________________
dense_9 (Dense)              (None, 2048)              2099200   
_________________________________________________________________
dropout_8 (Dropout)          (None, 2048)              0         
_________________________________________________________________
dense_10 (Dense)             (None, 1024)              2098176   
________

In [56]:
#compile network:
Prime_model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

In [57]:
#running network:
from keras.callbacks import ModelCheckpoint  

### TODO: specify the number of epochs that you would like to use to train the model.

epochs = 15

### Do NOT modify the code below this line.

checkpointer = ModelCheckpoint(filepath='D:\Machine Learning\LearningPrime/weights.best.from_scratch.hdf5', 
                               verbose=1, save_best_only=True)

Prime_model.fit(X_train, y_train, 
          validation_data=(X_test, y_test),
          epochs=epochs, batch_size=7, callbacks=[checkpointer], verbose=1)

Train on 7999 samples, validate on 2000 samples
Epoch 1/15
7999/7999 [==============================] - 240s - loss: 0.6540 - acc: 0.8690 - val_loss: 0.5304 - val_acc: 0.8740
Epoch 2/15
7999/7999 [==============================] - 311s - loss: 0.5564 - acc: 0.8751 - val_loss: 0.4488 - val_acc: 0.8740
Epoch 3/15
7999/7999 [==============================] - 339s - loss: 0.5853 - acc: 0.8750 - val_loss: 0.5245 - val_acc: 0.8740
Epoch 4/15
7999/7999 [==============================] - 348s - loss: 1.4468 - acc: 0.8771 - val_loss: 2.0198 - val_acc: 0.8740
Epoch 5/15
7999/7999 [==============================] - 398s - loss: 1.9579 - acc: 0.8779 - val_loss: 2.0198 - val_acc: 0.8740
Epoch 6/15
7999/7999 [==============================] - 367s - loss: 1.9579 - acc: 0.8779 - val_loss: 2.0198 - val_acc: 0.8740
Epoch 7/15
7999/7999 [==============================] - 367s - loss: 1.9579 - acc: 0.8779 - val_loss: 2.0198 - val_acc: 0.8740
Epoch 8/15
7999/7999 [==============================] - 380s - 

In [58]:
#prediction:
#load model
Prime_model.load_weights('D:\Machine Learning\LearningPrime/weights.best.from_scratch.hdf5')

In [59]:
def num(x, number):
    zeros=np.zeros(len(str(number)))
    for k in range((len(str(x)))):
        zeros[len(str(number))-k-1]=int(str(x)[len(str(x))-k-1])
    return(zeros)


#print(num(10, number))

In [60]:
def predPrime(x):
    #Prime_model.predict(np.array([num(x, number)]))
    #print(Prime_model.predict(np.array([num(x, number)]))[0])
    return(Prime_model.predict(np.array([num(x, number)]))[0][0],Prime_model.predict(np.array([num(x, number)]))[0][1])

In [68]:
for i in range(20):
    probNotPrime, probPrime= predPrime(prime[i])
    print('i=', prime[i], '  probNotPrime=', probNotPrime, '  probPrime=', probPrime)

for i in range(20):
    probNotPrime, probPrime= predPrime(prime[len(prime)-20+i])
    print('i=', prime[len(prime)-20+i], '  probNotPrime=', probNotPrime, '  probPrime=', probPrime)

i= 2   probNotPrime= 0.573034   probPrime= 0.426966
i= 3   probNotPrime= 0.594572   probPrime= 0.405428
i= 5   probNotPrime= 0.63793   probPrime= 0.36207
i= 7   probNotPrime= 0.681014   probPrime= 0.318986
i= 11   probNotPrime= 0.563027   probPrime= 0.436973
i= 13   probNotPrime= 0.595536   probPrime= 0.404463
i= 17   probNotPrime= 0.674138   probPrime= 0.325862
i= 19   probNotPrime= 0.712217   probPrime= 0.287783
i= 23   probNotPrime= 0.608589   probPrime= 0.391411
i= 29   probNotPrime= 0.71214   probPrime= 0.28786
i= 31   probNotPrime= 0.631549   probPrime= 0.368451
i= 37   probNotPrime= 0.683776   probPrime= 0.316224
i= 41   probNotPrime= 0.727679   probPrime= 0.272321
i= 43   probNotPrime= 0.657061   probPrime= 0.342939
i= 47   probNotPrime= 0.696884   probPrime= 0.303116
i= 53   probNotPrime= 0.693645   probPrime= 0.306355
i= 59   probNotPrime= 0.736804   probPrime= 0.263196
i= 61   probNotPrime= 0.968302   probPrime= 0.0316985
i= 67   probNotPrime= 0.732962   probPrime= 0.267038


In [67]:
#for i in notPrime:
#    probNotPrime, probPrime= predPrime(i)
#    print('i=', i, '  probNotPrime=', probNotPrime, '  probPrime=', probPrime)
    
    
for i in range(20):
    probNotPrime, probPrime= predPrime(notPrime[i])
    print('i=', notPrime[i], '  probNotPrime=', probNotPrime, '  probPrime=', probPrime)

for i in range(20):
    probNotPrime, probPrime= predPrime(notPrime[len(notPrime)-20+i])
    print('i=', notPrime[len(notPrime)-20+i], '  probNotPrime=', probNotPrime, '  probPrime=', probPrime)

i= 4   probNotPrime= 0.616196   probPrime= 0.383804
i= 6   probNotPrime= 0.659572   probPrime= 0.340428
i= 8   probNotPrime= 0.701881   probPrime= 0.298119
i= 9   probNotPrime= 0.721999   probPrime= 0.278001
i= 10   probNotPrime= 0.553452   probPrime= 0.446548
i= 12   probNotPrime= 0.578294   probPrime= 0.421706
i= 14   probNotPrime= 0.614339   probPrime= 0.385661
i= 15   probNotPrime= 0.634392   probPrime= 0.365608
i= 16   probNotPrime= 0.654435   probPrime= 0.345565
i= 18   probNotPrime= 0.69342   probPrime= 0.30658
i= 20   probNotPrime= 0.633584   probPrime= 0.366416
i= 21   probNotPrime= 0.587567   probPrime= 0.412434
i= 22   probNotPrime= 0.595603   probPrime= 0.404397
i= 24   probNotPrime= 0.623521   probPrime= 0.376479
i= 25   probNotPrime= 0.640277   probPrime= 0.359723
i= 26   probNotPrime= 0.657739   probPrime= 0.342261
i= 27   probNotPrime= 0.675764   probPrime= 0.324237
i= 28   probNotPrime= 0.694078   probPrime= 0.305922
i= 30   probNotPrime= 0.873373   probPrime= 0.126627

In [69]:
import math


In [70]:
#data1D=[]
notPrimeArray=[]

for i in numbers:
    #data1D.append(int(i[0]))
    #print (i)
    #print (int(i[0]))
    #print (2)
    #probNotPrime, probPrime=predPrime(int(i[0]))
    probNotPrime, probPrime=predPrime(i)
    notPrimeArray.append(probNotPrime)
    

#print(numbers)
#print(notPrimeArray)
    

In [71]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

labelArray=[]
for i in label:
    #print (i[0])
    labelArray.append(i[0])

notPrimeArray2D=[] 
for i in notPrimeArray:
    notPrimeArray2D.append([i])
    
#print (labelArray[0])    

X_train_boost, X_test_boost, y_train_boost, y_test_boost = train_test_split(notPrimeArray2D, labelArray, test_size=0.2, random_state=42)

clf=AdaBoostClassifier(n_estimators=50)

print (len(X_train_boost), len(y_train_boost))

#print (X_train_boost)
#print (y_train_boost)

clf.fit(X_train_boost, y_train_boost)




7999 7999


AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [72]:
def boostpredict(x):
    return(clf.predict(x))

In [73]:
accuracyPrime=0
for i in prime:
    probNotPrime, probPrime= predPrime(i)
    #print('i=', i, '  probNotPrime=', probNotPrime, '  probPrime=', probPrime)
    result=boostpredict(probNotPrime)
    #print('i=', i, '  probNotPrime=', result)
    if result==[1.]:
        accuracyPrime+=1

print(accuracyPrime/len(prime))


0.0016273393002441008


In [74]:
#for i in notPrime:
#    probNotPrime, probPrime= predPrime(i)
#    #print('i=', i, '  probNotPrime=', probNotPrime, '  probPrime=', probPrime)
#    print('i=', i, '  probNotPrime=', boostpredict(probNotPrime))
    
    
accuracyNotPrime=0
for i in notPrime:
    probNotPrime, probPrime= predPrime(i)
    #print('i=', i, '  probNotPrime=', probNotPrime, '  probPrime=', probPrime)
    result=boostpredict(probNotPrime)
    #print('i=', i, '  probNotPrime=', result)
    if result==[0.]:
        accuracyNotPrime+=1

print(accuracyNotPrime/len(notPrime))

1.0


In [330]:
def flatten_list(a, result=None):
    """Flattens a nested list.

        >>> flatten_list([ [1, 2, [3, 4] ], [5, 6], 7])
        [1, 2, 3, 4, 5, 6, 7]
    """
    print(a)
    if result is None:
        result = []

    for x in a:
        if isinstance(x, list):
            flatten_list(x, result)
        else:
            result.append(x)

    return result

a=[ [1, 2, [3, 4] ], [5, 6], 7]
print(flatten_list(a, result=None))

[[1, 2, [3, 4]], [5, 6], 7]
[1, 2, [3, 4]]
[3, 4]
[5, 6]
[1, 2, 3, 4, 5, 6, 7]


In [360]:
print (np.array([num(1, number)]))

[[ 0.  1.  0. ...,  0.  0.  0.]]


In [408]:
print(data)
print (predPrime(2))
probNotPrime, probPrime= predPrime(2)

print (probNotPrime*10)
a= (math.floor(probNotPrime*10))
b=math.floor(probNotPrime*100-a*10)
c=math.floor(probNotPrime*1000-(a*100+b*10))
d=math.floor(probNotPrime*10000-(a*1000+b*100+c*10))
e=math.floor(probNotPrime*100000-d*10)
f=math.floor(probNotPrime*1000000-e*10)
g=math.floor(probNotPrime*10000000-f*10)
h=math.floor(probNotPrime*100000000-g*10)
i=math.floor(probNotPrime*1000000000-h*10)
j=math.floor(probNotPrime*10000000000-i*10)

print ('a=', a)
print ('b=', b)
print ('c=', c)
print ('d=', d)
#print ('e=', e)

#print ('f=', f)
#print ('g=', g)
#print ('h=', h)
#print ('i=', i)
#print ('j=', j)

def digits(x,y):
    result=([math.floor(x*10)])
    if y>0:
        return(result.append(digits(x*10-math.floor(x*10),y-1)))
    else:
        return(result)
    
print (digits(probNotPrime, 1))
#    
#def digitsVect(x):

#for i in data:
    

[[  2.00000000e+00]
 [  3.00000000e+00]
 [  4.00000000e+00]
 ..., 
 [  4.99800000e+03]
 [  4.99900000e+03]
 [  5.00000000e+03]]
(0.84858251, 0.15141749)
8.4858250618
a= 8
b= 4
c= 8
d= 5
None
