In [1]:
def findPrime(x):
    prime=[2, 3] #
    notPrime=[]
    numbers=[2,3]
    exclude=4 #done to exclude 0 and 1 as they are unique numbers, exclude 2 and 3 as to get the list started.
    for i in range(x-exclude+1):
        num=i+exclude
        status=True
        
        for j in prime:
            if num%j==0:
                status=False
        numbers.append(num)
        if status:
            prime.append(num)
        else:
            notPrime.append(num)
    return(prime, notPrime, numbers)

number=15000
prime, notPrime,numbers=findPrime(number)
#pri
nt(prime, notPrime)

        

In [2]:
import numpy as np

label=np.zeros((number-1,1))
print(label)

[[ 0.]
 [ 0.]
 [ 0.]
 ..., 
 [ 0.]
 [ 0.]
 [ 0.]]


In [3]:
for i in prime:
    label[i-2]=1
#print(label)

from keras.utils import np_utils
label_final = np_utils.to_categorical(np.array(label), 2)
print(label)
print(label_final)

Using TensorFlow backend.


[[ 1.]
 [ 1.]
 [ 0.]
 ..., 
 [ 0.]
 [ 0.]
 [ 0.]]
[[ 0.  1.]
 [ 0.  1.]
 [ 1.  0.]
 ..., 
 [ 1.  0.]
 [ 1.  0.]
 [ 1.  0.]]


In [4]:
data=np.zeros((number-1,1))
for i in range(number-1):
    data[i]=i+2
#print(data)
data_final = np_utils.to_categorical(np.array(data), number+1)
print(data_final)

[[ 0.  0.  1. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  1.  0.  0.]
 [ 0.  0.  0. ...,  0.  1.  0.]
 [ 0.  0.  0. ...,  0.  0.  1.]]


In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data_final, label_final, test_size=0.2, random_state=42)

In [6]:
from sklearn.ensemble import AdaBoostClassifier








In [7]:
#neural network(s):
from keras.layers import Conv1D, MaxPooling1D, GlobalAveragePooling1D, AveragePooling1D
from keras.layers import Dropout, Flatten, Dense
from keras.models import Sequential

print(X_train.shape[1])

Prime_model = Sequential()
Prime_model.add(Dense(512, input_shape=(X_train.shape[1],)))
Prime_model.add(Dropout(.3))
Prime_model.add(Dense(512, activation='relu'))
Prime_model.add(Dropout(.3))
Prime_model.add(Dense(512, activation='relu'))
Prime_model.add(Dropout(.3))
Prime_model.add(Dense(512, activation='relu'))
Prime_model.add(Dropout(.3))
Prime_model.add(Dense(512, activation='relu'))
Prime_model.add(Dropout(.3))
#Prime_model.add(Dense(256, activation='relu'))
#Prime_model.add(Dropout(.3))
#Prime_model.add(Dense(128, activation='relu'))
#Prime_model.add(Dropout(.3))
#Prime_model.add(Dense(64, activation='relu'))
#Prime_model.add(Dropout(.3))
#Prime_model.add(Dense(32, activation='relu'))
#Prime_model.add(Dropout(.3))
#Prime_model.add(Dense(16, activation='relu'))
#Prime_model.add(Dropout(.3))
#Prime_model.add(Dense(8, activation='relu'))
#Prime_model.add(Dropout(.3))
#Prime_model.add(Dense(4, activation='relu'))
#Prime_model.add(Dropout(.3))
Prime_model.add(Dense(2, activation='softmax'))
Prime_model.summary()

15001
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 512)               7681024   
_________________________________________________________________
dropout_1 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 512)               262656    
_________________________________________________________________
dropout_2 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 512)               262656    
_________________________________________________________________
dropout_3 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 512)               262656    
____

In [8]:
#compile network:
Prime_model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

In [9]:
#running network:
from keras.callbacks import ModelCheckpoint  

### TODO: specify the number of epochs that you would like to use to train the model.

epochs = 15

### Do NOT modify the code below this line.

checkpointer = ModelCheckpoint(filepath='D:\Machine Learning\LearningPrime/weights.best.from_scratch.hdf5', 
                               verbose=1, save_best_only=True)

Prime_model.fit(X_train, y_train, 
          validation_data=(X_test, y_test),
          epochs=epochs, batch_size=7, callbacks=[checkpointer], verbose=1)

Train on 11999 samples, validate on 3000 samples
Epoch 1/15
11999/11999 [==============================] - 570s - loss: 0.4096 - acc: 0.8822 - val_loss: 0.3701 - val_acc: 0.8843
Epoch 2/15
11999/11999 [==============================] - 719s - loss: 0.3913 - acc: 0.8827 - val_loss: 0.3610 - val_acc: 0.8843
Epoch 3/15
11999/11999 [==============================] - 742s - loss: 0.3067 - acc: 0.8893 - val_loss: 1.0254 - val_acc: 0.1193
Epoch 4/15
11999/11999 [==============================] - 753s - loss: 0.0986 - acc: 0.9758 - val_loss: 10.1101 - val_acc: 0.1157
Epoch 5/15
11999/11999 [==============================] - 762s - loss: 0.1092 - acc: 0.9820 - val_loss: 6.8722 - val_acc: 0.1477
Epoch 6/15
11999/11999 [==============================] - 766s - loss: 0.0730 - acc: 0.9871 - val_loss: 10.9191 - val_acc: 0.1537
Epoch 7/15
11999/11999 [==============================] - 771s - loss: 0.0594 - acc: 0.9948 - val_loss: 10.7912 - val_acc: 0.2267
Epoch 8/15
11999/11999 [=====================

In [445]:
#prediction:
#load model
Prime_model.load_weights('D:\Machine Learning\LearningPrime/weights.best.from_scratch.hdf5')

In [446]:
def num(x, number):
    zeros=np.zeros(number+1)
    zeros[x]=1
    #print(zeros)
    return(zeros)

In [447]:
def predPrime(x):
    #Prime_model.predict(np.array([num(x, number)]))
    #print(Prime_model.predict(np.array([num(x, number)]))[0])
    return(Prime_model.predict(np.array([num(x, number)]))[0][0],Prime_model.predict(np.array([num(x, number)]))[0][1])

In [432]:
for i in prime:
    probNotPrime, probPrime= predPrime(i)
    print('i=', i, '  probNotPrime=', probNotPrime, '  probPrime=', probPrime)

i= 2   probNotPrime= 0.942218   probPrime= 0.057782
i= 3   probNotPrime= 0.886843   probPrime= 0.113156
i= 5   probNotPrime= 0.950909   probPrime= 0.0490914
i= 7   probNotPrime= 0.846183   probPrime= 0.153817
i= 11   probNotPrime= 0.899043   probPrime= 0.100957
i= 13   probNotPrime= 0.931009   probPrime= 0.0689913
i= 17   probNotPrime= 0.93256   probPrime= 0.06744
i= 19   probNotPrime= 0.938623   probPrime= 0.0613769
i= 23   probNotPrime= 0.949103   probPrime= 0.0508975
i= 29   probNotPrime= 0.954678   probPrime= 0.0453222
i= 31   probNotPrime= 0.956674   probPrime= 0.043326
i= 37   probNotPrime= 0.936539   probPrime= 0.0634612
i= 41   probNotPrime= 0.948375   probPrime= 0.0516255
i= 43   probNotPrime= 0.916659   probPrime= 0.0833414
i= 47   probNotPrime= 0.886037   probPrime= 0.113963
i= 53   probNotPrime= 0.871208   probPrime= 0.128792
i= 59   probNotPrime= 0.951909   probPrime= 0.0480913
i= 61   probNotPrime= 0.945425   probPrime= 0.0545747
i= 67   probNotPrime= 0.918405   probPrime

In [448]:
for i in notPrime:
    probNotPrime, probPrime= predPrime(i)
    print('i=', i, '  probNotPrime=', probNotPrime, '  probPrime=', probPrime)

i= 4   probNotPrime= 0.949716   probPrime= 0.050284
i= 6   probNotPrime= 0.913952   probPrime= 0.0860482
i= 8   probNotPrime= 0.924286   probPrime= 0.0757136
i= 9   probNotPrime= 0.925241   probPrime= 0.074759
i= 10   probNotPrime= 0.834407   probPrime= 0.165593
i= 12   probNotPrime= 0.966232   probPrime= 0.0337685
i= 14   probNotPrime= 0.993831   probPrime= 0.00616953
i= 15   probNotPrime= 0.982122   probPrime= 0.0178778
i= 16   probNotPrime= 0.882274   probPrime= 0.117726
i= 18   probNotPrime= 0.952872   probPrime= 0.0471277
i= 20   probNotPrime= 0.992604   probPrime= 0.00739563
i= 21   probNotPrime= 0.937015   probPrime= 0.0629853
i= 22   probNotPrime= 0.948861   probPrime= 0.0511393
i= 24   probNotPrime= 0.953942   probPrime= 0.0460578
i= 25   probNotPrime= 0.952159   probPrime= 0.047841
i= 26   probNotPrime= 0.950289   probPrime= 0.0497108
i= 27   probNotPrime= 0.917469   probPrime= 0.0825306
i= 28   probNotPrime= 0.966711   probPrime= 0.0332889
i= 30   probNotPrime= 0.962962   pr

In [449]:
import math


In [450]:
#data1D=[]
notPrimeArray=[]

for i in numbers:
    #data1D.append(int(i[0]))
    #print (i)
    #print (int(i[0]))
    #print (2)
    #probNotPrime, probPrime=predPrime(int(i[0]))
    probNotPrime, probPrime=predPrime(i)
    notPrimeArray.append(probNotPrime)
    

#print(numbers)
#print(notPrimeArray)
    

In [451]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

labelArray=[]
for i in label:
    #print (i[0])
    labelArray.append(i[0])

notPrimeArray2D=[] 
for i in notPrimeArray:
    notPrimeArray2D.append([i])
    
#print (labelArray[0])    

X_train_boost, X_test_boost, y_train_boost, y_test_boost = train_test_split(notPrimeArray2D, labelArray, test_size=0.2, random_state=42)

clf=AdaBoostClassifier(n_estimators=50)

print (len(X_train_boost), len(y_train_boost))

#print (X_train_boost)
#print (y_train_boost)

clf.fit(X_train_boost, y_train_boost)




7199 7199


AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [452]:
def boostpredict(x):
    return(clf.predict(x))

In [453]:
accuracyPrime=0
for i in prime:
    probNotPrime, probPrime= predPrime(i)
    #print('i=', i, '  probNotPrime=', probNotPrime, '  probPrime=', probPrime)
    result=boostpredict(probNotPrime)
    #print('i=', i, '  probNotPrime=', result)
    if result==[1.]:
        accuracyPrime+=1

print(accuracyPrime/len(prime))


0.5729632945389436


In [454]:
#for i in notPrime:
#    probNotPrime, probPrime= predPrime(i)
#    #print('i=', i, '  probNotPrime=', probNotPrime, '  probPrime=', probPrime)
#    print('i=', i, '  probNotPrime=', boostpredict(probNotPrime))
    
    
accuracyNotPrime=0
for i in notPrime:
    probNotPrime, probPrime= predPrime(i)
    #print('i=', i, '  probNotPrime=', probNotPrime, '  probPrime=', probPrime)
    result=boostpredict(probNotPrime)
    #print('i=', i, '  probNotPrime=', result)
    if result==[0.]:
        accuracyNotPrime+=1

print(accuracyNotPrime/len(notPrime))

0.9124587668104542


In [330]:
def flatten_list(a, result=None):
    """Flattens a nested list.

        >>> flatten_list([ [1, 2, [3, 4] ], [5, 6], 7])
        [1, 2, 3, 4, 5, 6, 7]
    """
    print(a)
    if result is None:
        result = []

    for x in a:
        if isinstance(x, list):
            flatten_list(x, result)
        else:
            result.append(x)

    return result

a=[ [1, 2, [3, 4] ], [5, 6], 7]
print(flatten_list(a, result=None))

[[1, 2, [3, 4]], [5, 6], 7]
[1, 2, [3, 4]]
[3, 4]
[5, 6]
[1, 2, 3, 4, 5, 6, 7]


In [360]:
print (np.array([num(1, number)]))

[[ 0.  1.  0. ...,  0.  0.  0.]]


In [408]:
print(data)
print (predPrime(2))
probNotPrime, probPrime= predPrime(2)

print (probNotPrime*10)
a= (math.floor(probNotPrime*10))
b=math.floor(probNotPrime*100-a*10)
c=math.floor(probNotPrime*1000-(a*100+b*10))
d=math.floor(probNotPrime*10000-(a*1000+b*100+c*10))
e=math.floor(probNotPrime*100000-d*10)
f=math.floor(probNotPrime*1000000-e*10)
g=math.floor(probNotPrime*10000000-f*10)
h=math.floor(probNotPrime*100000000-g*10)
i=math.floor(probNotPrime*1000000000-h*10)
j=math.floor(probNotPrime*10000000000-i*10)

print ('a=', a)
print ('b=', b)
print ('c=', c)
print ('d=', d)
#print ('e=', e)

#print ('f=', f)
#print ('g=', g)
#print ('h=', h)
#print ('i=', i)
#print ('j=', j)

def digits(x,y):
    result=([math.floor(x*10)])
    if y>0:
        return(result.append(digits(x*10-math.floor(x*10),y-1)))
    else:
        return(result)
    
print (digits(probNotPrime, 1))
#    
#def digitsVect(x):

#for i in data:
    

[[  2.00000000e+00]
 [  3.00000000e+00]
 [  4.00000000e+00]
 ..., 
 [  4.99800000e+03]
 [  4.99900000e+03]
 [  5.00000000e+03]]
(0.84858251, 0.15141749)
8.4858250618
a= 8
b= 4
c= 8
d= 5
None
