In [420]:
def findPrime(x):
    prime=[2, 3] #
    notPrime=[]
    numbers=[2,3]
    exclude=4 #done to exclude 0 and 1 as they are unique numbers, exclude 2 and 3 as to get the list started.
    for i in range(x-exclude+1):
        num=i+exclude
        status=True
        
        for j in prime:
            if num%j==0:
                status=False
        numbers.append(num)
        if status:
            prime.append(num)
        else:
            notPrime.append(num)
    return(prime, notPrime, numbers)

number=10000
prime, notPrime,numbers=findPrime(number)
#print(prime, notPrime)

        

In [421]:
import numpy as np

label=np.zeros((number-1,1))
print(label)

[[ 0.]
 [ 0.]
 [ 0.]
 ..., 
 [ 0.]
 [ 0.]
 [ 0.]]


In [422]:
for i in prime:
    label[i-2]=1
#print(label)

from keras.utils import np_utils
label_final = np_utils.to_categorical(np.array(label), 2)
print(label)
print(label_final)

[[ 1.]
 [ 1.]
 [ 0.]
 ..., 
 [ 0.]
 [ 1.]
 [ 0.]]
[[ 0.  1.]
 [ 0.  1.]
 [ 1.  0.]
 ..., 
 [ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]]


In [423]:
data=np.zeros((number-1,len(str(number))))
for i in range(number-1):
    for k in range(len(str(i))):
        data[i][k]=int(str(i)[len(str(number))-k])
#print(data)
#data_final = np_utils.to_categorical(np.array(data), number+1)
print(data_final)

[[ 0.  0.  1. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  1.  0.  0.]
 [ 0.  0.  0. ...,  0.  1.  0.]
 [ 0.  0.  0. ...,  0.  0.  1.]]


In [424]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data_final, label_final, test_size=0.2, random_state=42)

In [425]:
from sklearn.ensemble import AdaBoostClassifier








In [440]:
#neural network(s):
from keras.layers import Conv1D, MaxPooling1D, GlobalAveragePooling1D, AveragePooling1D
from keras.layers import Dropout, Flatten, Dense
from keras.models import Sequential

print(X_train.shape[1])

Prime_model = Sequential()
Prime_model.add(Dense(512, input_shape=(X_train.shape[1],)))
Prime_model.add(Dropout(.3))
Prime_model.add(Dense(512, activation='relu'))
Prime_model.add(Dropout(.3))
Prime_model.add(Dense(512, activation='relu'))
Prime_model.add(Dropout(.3))
Prime_model.add(Dense(512, activation='relu'))
Prime_model.add(Dropout(.3))
Prime_model.add(Dense(512, activation='relu'))
Prime_model.add(Dropout(.3))
#Prime_model.add(Dense(256, activation='relu'))
#Prime_model.add(Dropout(.3))
#Prime_model.add(Dense(128, activation='relu'))
#Prime_model.add(Dropout(.3))
#Prime_model.add(Dense(64, activation='relu'))
#Prime_model.add(Dropout(.3))
#Prime_model.add(Dense(32, activation='relu'))
#Prime_model.add(Dropout(.3))
#Prime_model.add(Dense(16, activation='relu'))
#Prime_model.add(Dropout(.3))
#Prime_model.add(Dense(8, activation='relu'))
#Prime_model.add(Dropout(.3))
#Prime_model.add(Dense(4, activation='relu'))
#Prime_model.add(Dropout(.3))
Prime_model.add(Dense(2, activation='softmax'))
Prime_model.summary()

9001
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_83 (Dense)             (None, 512)               4609024   
_________________________________________________________________
dropout_53 (Dropout)         (None, 512)               0         
_________________________________________________________________
dense_84 (Dense)             (None, 512)               262656    
_________________________________________________________________
dropout_54 (Dropout)         (None, 512)               0         
_________________________________________________________________
dense_85 (Dense)             (None, 512)               262656    
_________________________________________________________________
dropout_55 (Dropout)         (None, 512)               0         
_________________________________________________________________
dense_86 (Dense)             (None, 512)               262656    
_____

In [441]:
#compile network:
Prime_model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
#running network:
from keras.callbacks import ModelCheckpoint  

### TODO: specify the number of epochs that you would like to use to train the model.

epochs = 15

### Do NOT modify the code below this line.

checkpointer = ModelCheckpoint(filepath='D:\Machine Learning\LearningPrime/weights.best.from_scratch.hdf5', 
                               verbose=1, save_best_only=True)

Prime_model.fit(X_train, y_train, 
          validation_data=(X_test, y_test),
          epochs=epochs, batch_size=7, callbacks=[checkpointer], verbose=1)

Train on 7199 samples, validate on 1800 samples
Epoch 1/15
7199/7199 [==============================] - 287s - loss: 0.3982 - acc: 0.8754 - val_loss: 0.3878 - val_acc: 0.8778
Epoch 2/15
7199/7199 [==============================] - 289s - loss: 0.2362 - acc: 0.9078 - val_loss: 1.7420 - val_acc: 0.3261
Epoch 3/15
7199/7199 [==============================] - 294s - loss: 0.0909 - acc: 0.9757 - val_loss: 5.8259 - val_acc: 0.1489
Epoch 4/15
7199/7199 [==============================] - 298s - loss: 0.0642 - acc: 0.9862 - val_loss: 5.7495 - val_acc: 0.2822
Epoch 5/15
7199/7199 [==============================] - 297s - loss: 0.0790 - acc: 0.9850 - val_loss: 9.5117 - val_acc: 0.1678
Epoch 6/15
7199/7199 [==============================] - 299s - loss: 0.0550 - acc: 0.9901 - val_loss: 13.1790 - val_acc: 0.1339
Epoch 7/15
7199/7199 [==============================] - 302s - loss: 0.0593 - acc: 0.9917 - val_loss: 1.8786 - val_acc: 0.8700
Epoch 8/15
7199/7199 [==============================] - 301s -

In [443]:
#prediction:
#load model
Prime_model.load_weights('D:\Machine Learning\LearningPrime/weights.best.from_scratch.hdf5')

In [430]:
def num(x, number):
    zeros=np.zeros(number+1)
    zeros[x]=1
    #print(zeros)
    return(zeros)

In [431]:
def predPrime(x):
    #Prime_model.predict(np.array([num(x, number)]))
    #print(Prime_model.predict(np.array([num(x, number)]))[0])
    return(Prime_model.predict(np.array([num(x, number)]))[0][0],Prime_model.predict(np.array([num(x, number)]))[0][1])

In [432]:
for i in prime:
    probNotPrime, probPrime= predPrime(i)
    print('i=', i, '  probNotPrime=', probNotPrime, '  probPrime=', probPrime)

i= 2   probNotPrime= 0.942218   probPrime= 0.057782
i= 3   probNotPrime= 0.886843   probPrime= 0.113156
i= 5   probNotPrime= 0.950909   probPrime= 0.0490914
i= 7   probNotPrime= 0.846183   probPrime= 0.153817
i= 11   probNotPrime= 0.899043   probPrime= 0.100957
i= 13   probNotPrime= 0.931009   probPrime= 0.0689913
i= 17   probNotPrime= 0.93256   probPrime= 0.06744
i= 19   probNotPrime= 0.938623   probPrime= 0.0613769
i= 23   probNotPrime= 0.949103   probPrime= 0.0508975
i= 29   probNotPrime= 0.954678   probPrime= 0.0453222
i= 31   probNotPrime= 0.956674   probPrime= 0.043326
i= 37   probNotPrime= 0.936539   probPrime= 0.0634612
i= 41   probNotPrime= 0.948375   probPrime= 0.0516255
i= 43   probNotPrime= 0.916659   probPrime= 0.0833414
i= 47   probNotPrime= 0.886037   probPrime= 0.113963
i= 53   probNotPrime= 0.871208   probPrime= 0.128792
i= 59   probNotPrime= 0.951909   probPrime= 0.0480913
i= 61   probNotPrime= 0.945425   probPrime= 0.0545747
i= 67   probNotPrime= 0.918405   probPrime

In [433]:
for i in notPrime:
    probNotPrime, probPrime= predPrime(i)
    print('i=', i, '  probNotPrime=', probNotPrime, '  probPrime=', probPrime)

i= 4   probNotPrime= 0.946818   probPrime= 0.0531824
i= 6   probNotPrime= 0.944479   probPrime= 0.0555215
i= 8   probNotPrime= 0.941317   probPrime= 0.0586826
i= 9   probNotPrime= 0.954609   probPrime= 0.0453913
i= 10   probNotPrime= 0.948507   probPrime= 0.0514933
i= 12   probNotPrime= 0.945666   probPrime= 0.0543336
i= 14   probNotPrime= 0.950616   probPrime= 0.0493841
i= 15   probNotPrime= 0.925779   probPrime= 0.0742205
i= 16   probNotPrime= 0.932684   probPrime= 0.0673162
i= 18   probNotPrime= 0.949376   probPrime= 0.0506245
i= 20   probNotPrime= 0.948736   probPrime= 0.0512636
i= 21   probNotPrime= 0.93162   probPrime= 0.0683804
i= 22   probNotPrime= 0.957575   probPrime= 0.0424251
i= 24   probNotPrime= 0.911923   probPrime= 0.0880766
i= 25   probNotPrime= 0.926144   probPrime= 0.0738555
i= 26   probNotPrime= 0.973536   probPrime= 0.0264642
i= 27   probNotPrime= 0.917085   probPrime= 0.0829146
i= 28   probNotPrime= 0.959031   probPrime= 0.0409687
i= 30   probNotPrime= 0.962547   

In [434]:
import math


In [435]:
#data1D=[]
notPrimeArray=[]

for i in numbers:
    #data1D.append(int(i[0]))
    #print (i)
    #print (int(i[0]))
    #print (2)
    #probNotPrime, probPrime=predPrime(int(i[0]))
    probNotPrime, probPrime=predPrime(i)
    notPrimeArray.append(probNotPrime)
    

#print(numbers)
#print(notPrimeArray)
    

In [436]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

labelArray=[]
for i in label:
    #print (i[0])
    labelArray.append(i[0])

notPrimeArray2D=[] 
for i in notPrimeArray:
    notPrimeArray2D.append([i])
    
#print (labelArray[0])    

X_train_boost, X_test_boost, y_train_boost, y_test_boost = train_test_split(notPrimeArray2D, labelArray, test_size=0.2, random_state=42)

clf=AdaBoostClassifier(n_estimators=50)

print (len(X_train_boost), len(y_train_boost))

#print (X_train_boost)
#print (y_train_boost)

clf.fit(X_train_boost, y_train_boost)




7199 7199


AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [437]:
def boostpredict(x):
    return(clf.predict(x))

In [438]:
accuracyPrime=0
for i in prime:
    probNotPrime, probPrime= predPrime(i)
    #print('i=', i, '  probNotPrime=', probNotPrime, '  probPrime=', probPrime)
    result=boostpredict(probNotPrime)
    #print('i=', i, '  probNotPrime=', result)
    if result==[1.]:
        accuracyPrime+=1

print(accuracyPrime/len(prime))


0.18263205013428827


In [439]:
#for i in notPrime:
#    probNotPrime, probPrime= predPrime(i)
#    #print('i=', i, '  probNotPrime=', probNotPrime, '  probPrime=', probPrime)
#    print('i=', i, '  probNotPrime=', boostpredict(probNotPrime))
    
    
accuracyNotPrime=0
for i in notPrime:
    probNotPrime, probPrime= predPrime(i)
    #print('i=', i, '  probNotPrime=', probNotPrime, '  probPrime=', probPrime)
    result=boostpredict(probNotPrime)
    #print('i=', i, '  probNotPrime=', result)
    if result==[0.]:
        accuracyNotPrime+=1

print(accuracyNotPrime/len(notPrime))

0.9914996193859427


In [330]:
def flatten_list(a, result=None):
    """Flattens a nested list.

        >>> flatten_list([ [1, 2, [3, 4] ], [5, 6], 7])
        [1, 2, 3, 4, 5, 6, 7]
    """
    print(a)
    if result is None:
        result = []

    for x in a:
        if isinstance(x, list):
            flatten_list(x, result)
        else:
            result.append(x)

    return result

a=[ [1, 2, [3, 4] ], [5, 6], 7]
print(flatten_list(a, result=None))

[[1, 2, [3, 4]], [5, 6], 7]
[1, 2, [3, 4]]
[3, 4]
[5, 6]
[1, 2, 3, 4, 5, 6, 7]


In [360]:
print (np.array([num(1, number)]))

[[ 0.  1.  0. ...,  0.  0.  0.]]


In [408]:
print(data)
print (predPrime(2))
probNotPrime, probPrime= predPrime(2)

print (probNotPrime*10)
a= (math.floor(probNotPrime*10))
b=math.floor(probNotPrime*100-a*10)
c=math.floor(probNotPrime*1000-(a*100+b*10))
d=math.floor(probNotPrime*10000-(a*1000+b*100+c*10))
e=math.floor(probNotPrime*100000-d*10)
f=math.floor(probNotPrime*1000000-e*10)
g=math.floor(probNotPrime*10000000-f*10)
h=math.floor(probNotPrime*100000000-g*10)
i=math.floor(probNotPrime*1000000000-h*10)
j=math.floor(probNotPrime*10000000000-i*10)

print ('a=', a)
print ('b=', b)
print ('c=', c)
print ('d=', d)
#print ('e=', e)

#print ('f=', f)
#print ('g=', g)
#print ('h=', h)
#print ('i=', i)
#print ('j=', j)

def digits(x,y):
    result=([math.floor(x*10)])
    if y>0:
        return(result.append(digits(x*10-math.floor(x*10),y-1)))
    else:
        return(result)
    
print (digits(probNotPrime, 1))
#    
#def digitsVect(x):

#for i in data:
    

[[  2.00000000e+00]
 [  3.00000000e+00]
 [  4.00000000e+00]
 ..., 
 [  4.99800000e+03]
 [  4.99900000e+03]
 [  5.00000000e+03]]
(0.84858251, 0.15141749)
8.4858250618
a= 8
b= 4
c= 8
d= 5
None
