In [3]:
def findPrime(x):
    prime=[2, 3] #
    notPrime=[]
    numbers=[2,3]
    exclude=4 #done to exclude 0 and 1 as they are unique numbers, exclude 2 and 3 as to get the list started.
    for i in range(x-exclude+1):
        num=i+exclude
        status=True
        
        for j in prime:
            if num%j==0:
                status=False
        numbers.append(num)
        if status:
            prime.append(num)
        else:
            notPrime.append(num)
    return(prime, notPrime, numbers)

number=10000
prime, notPrime,numbers=findPrime(number)
#print(prime, notPrime)

        

In [4]:
import numpy as np

label=np.zeros((number-1,1))
print(label)

[[ 0.]
 [ 0.]
 [ 0.]
 ..., 
 [ 0.]
 [ 0.]
 [ 0.]]


In [5]:
for i in prime:
    label[i-2]=1
#print(label)

from keras.utils import np_utils
label_final = np_utils.to_categorical(np.array(label), 2)
print(label)
print(label_final)

[[ 1.]
 [ 1.]
 [ 0.]
 ..., 
 [ 0.]
 [ 0.]
 [ 0.]]
[[ 0.  1.]
 [ 0.  1.]
 [ 1.  0.]
 ..., 
 [ 1.  0.]
 [ 1.  0.]
 [ 1.  0.]]


In [14]:
data=np.zeros((number-1,1,len(str(number))))
for i in range(number-1):
    num=i+2
    for k in range(len(str(num))):
        data[i][0][len(str(number))-k-1]=int(str(num)[len(str(num))-k-1])
#print(data)
#data_final = np_utils.to_categorical(np.array(data), number+1)
print(data)

[[[ 0.  0.  0.  0.  2.]]

 [[ 0.  0.  0.  0.  3.]]

 [[ 0.  0.  0.  0.  4.]]

 ..., 
 [[ 0.  9.  9.  9.  8.]]

 [[ 0.  9.  9.  9.  9.]]

 [[ 1.  0.  0.  0.  0.]]]


In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, label_final, test_size=0.2, random_state=42)

In [8]:
from sklearn.ensemble import AdaBoostClassifier








In [73]:
#neural network(s):
from keras.layers import Conv1D, MaxPooling1D, GlobalAveragePooling1D, AveragePooling1D
from keras.layers import Dropout, Flatten, Dense
from keras.models import Sequential

print(X_train.shape)

Prime_model = Sequential()
Prime_model.add(Conv1D(filters=256, kernel_size=5, padding='same', activation='relu', input_shape=(X_train.shape[1],X_train.shape[2])))
#Prime_model.add(MaxPooling1D(pool_size=2))
Prime_model.add(Conv1D(filters=512, kernel_size=2, padding='same', activation='relu'))
#Prime_model.add(MaxPooling1D(pool_size=2))
Prime_model.add(Conv1D(filters=1024, kernel_size=1, padding='same', activation='relu'))
#Prime_model.add(MaxPooling1D(pool_size=4))
#Prime_model.add(AveragePooling1D(pool_size=(2, 2), strides=None, padding='valid'))
Prime_model.add(Dropout(.3))
Prime_model.add(Flatten())
Prime_model.add(Dense(2, activation='softmax'))

Prime_model.summary()

(7999, 1, 5)
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_25 (Conv1D)           (None, 1, 256)            6656      
_________________________________________________________________
conv1d_26 (Conv1D)           (None, 1, 512)            262656    
_________________________________________________________________
conv1d_27 (Conv1D)           (None, 1, 1024)           525312    
_________________________________________________________________
dropout_6 (Dropout)          (None, 1, 1024)           0         
_________________________________________________________________
flatten_6 (Flatten)          (None, 1024)              0         
_________________________________________________________________
dense_6 (Dense)              (None, 2)                 2050      
Total params: 796,674.0
Trainable params: 796,674.0
Non-trainable params: 0.0
___________________________________________________

In [74]:
#compile network:
Prime_model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

In [75]:
#running network:
from keras.callbacks import ModelCheckpoint  

### TODO: specify the number of epochs that you would like to use to train the model.

epochs = 15

### Do NOT modify the code below this line.

checkpointer = ModelCheckpoint(filepath='D:\Machine Learning\LearningPrime/weights.best.from_scratch.hdf5', 
                               verbose=1, save_best_only=True)

Prime_model.fit(X_train, y_train, 
          validation_data=(X_test, y_test),
          epochs=epochs, batch_size=7, callbacks=[checkpointer], verbose=1)

Train on 7999 samples, validate on 2000 samples
Epoch 1/15
7999/7999 [==============================] - 51s - loss: 0.3938 - acc: 0.8774 - val_loss: 0.4161 - val_acc: 0.8740
Epoch 2/15
7999/7999 [==============================] - 58s - loss: 0.3784 - acc: 0.8779 - val_loss: 0.3666 - val_acc: 0.8740
Epoch 3/15
7999/7999 [==============================] - 58s - loss: 0.3745 - acc: 0.8779 - val_loss: 0.3668 - val_acc: 0.8740
Epoch 4/15
7999/7999 [==============================] - 59s - loss: 0.3767 - acc: 0.8779 - val_loss: 0.3623 - val_acc: 0.8740
Epoch 5/15
7999/7999 [==============================] - 61s - loss: 0.3757 - acc: 0.8779 - val_loss: 0.3669 - val_acc: 0.8740
Epoch 6/15
7999/7999 [==============================] - 64s - loss: 0.3853 - acc: 0.8779 - val_loss: 0.3644 - val_acc: 0.8740
Epoch 7/15
7999/7999 [==============================] - 65s - loss: 0.3619 - acc: 0.8779 - val_loss: 0.3634 - val_acc: 0.8740
Epoch 8/15
7999/7999 [==============================] - 64s - loss: 0.

In [76]:
#prediction:
#load model
Prime_model.load_weights('D:\Machine Learning\LearningPrime/weights.best.from_scratch.hdf5')

In [77]:
def num(x, number):
    zeros=np.zeros(len(str(number)))
    for k in range((len(str(x)))):
        zeros[len(str(number))-k-1]=int(str(x)[len(str(x))-k-1])
    return(np.array([zeros]))


print(num(10, number))

[[ 0.  0.  0.  1.  0.]]


In [78]:
def predPrime(x):
    #Prime_model.predict(np.array([num(x, number)]))
    #print(Prime_model.predict(np.array([num(x, number)]))[0])
    return(Prime_model.predict(np.array([num(x, number)]))[0][0],Prime_model.predict(np.array([num(x, number)]))[0][1])

In [79]:
for i in range(20):
    probNotPrime, probPrime= predPrime(prime[i])
    print('i=', prime[i], '  probNotPrime=', probNotPrime, '  probPrime=', probPrime)

for i in range(20):
    probNotPrime, probPrime= predPrime(prime[len(prime)-20+i])
    print('i=', prime[len(prime)-20+i], '  probNotPrime=', probNotPrime, '  probPrime=', probPrime)

i= 2   probNotPrime= 0.819416   probPrime= 0.180584
i= 3   probNotPrime= 0.845458   probPrime= 0.154542
i= 5   probNotPrime= 0.861089   probPrime= 0.138911
i= 7   probNotPrime= 0.861089   probPrime= 0.138911
i= 11   probNotPrime= 0.785131   probPrime= 0.214869
i= 13   probNotPrime= 0.850336   probPrime= 0.149664
i= 17   probNotPrime= 0.861089   probPrime= 0.138911
i= 19   probNotPrime= 0.861089   probPrime= 0.138911
i= 23   probNotPrime= 0.854452   probPrime= 0.145548
i= 29   probNotPrime= 0.861089   probPrime= 0.138911
i= 31   probNotPrime= 0.774074   probPrime= 0.225926
i= 37   probNotPrime= 0.861089   probPrime= 0.138911
i= 41   probNotPrime= 0.759308   probPrime= 0.240692
i= 43   probNotPrime= 0.851214   probPrime= 0.148786
i= 47   probNotPrime= 0.861089   probPrime= 0.138911
i= 53   probNotPrime= 0.847792   probPrime= 0.152208
i= 59   probNotPrime= 0.861089   probPrime= 0.138911
i= 61   probNotPrime= 0.729192   probPrime= 0.270808
i= 67   probNotPrime= 0.861089   probPrime= 0.1389

In [80]:
#for i in notPrime:
#    probNotPrime, probPrime= predPrime(i)
#    print('i=', i, '  probNotPrime=', probNotPrime, '  probPrime=', probPrime)
    
    
for i in range(20):
    probNotPrime, probPrime= predPrime(notPrime[i])
    print('i=', notPrime[i], '  probNotPrime=', probNotPrime, '  probPrime=', probPrime)

for i in range(20):
    probNotPrime, probPrime= predPrime(notPrime[len(notPrime)-20+i])
    print('i=', notPrime[len(notPrime)-20+i], '  probNotPrime=', probNotPrime, '  probPrime=', probPrime)

i= 4   probNotPrime= 0.861089   probPrime= 0.138911
i= 6   probNotPrime= 0.861089   probPrime= 0.138911
i= 8   probNotPrime= 0.861089   probPrime= 0.138911
i= 9   probNotPrime= 0.861089   probPrime= 0.138911
i= 10   probNotPrime= 1.0   probPrime= 1.22442e-12
i= 12   probNotPrime= 0.826661   probPrime= 0.173339
i= 14   probNotPrime= 0.861089   probPrime= 0.138911
i= 15   probNotPrime= 0.861089   probPrime= 0.138911
i= 16   probNotPrime= 0.861089   probPrime= 0.138911
i= 18   probNotPrime= 0.861089   probPrime= 0.138911
i= 20   probNotPrime= 1.0   probPrime= 1.26332e-12
i= 21   probNotPrime= 0.779344   probPrime= 0.220656
i= 22   probNotPrime= 0.826933   probPrime= 0.173067
i= 24   probNotPrime= 0.861089   probPrime= 0.138911
i= 25   probNotPrime= 0.861089   probPrime= 0.138911
i= 26   probNotPrime= 0.861089   probPrime= 0.138911
i= 27   probNotPrime= 0.861089   probPrime= 0.138911
i= 28   probNotPrime= 0.861089   probPrime= 0.138911
i= 30   probNotPrime= 1.0   probPrime= 5.70978e-13
i= 

In [59]:
import math


In [81]:
#data1D=[]
notPrimeArray=[]

for i in numbers:
    #data1D.append(int(i[0]))
    #print (i)
    #print (int(i[0]))
    #print (2)
    #probNotPrime, probPrime=predPrime(int(i[0]))
    probNotPrime, probPrime=predPrime(i)
    notPrimeArray.append(probNotPrime)
    

#print(numbers)
#print(notPrimeArray)
    

In [82]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

labelArray=[]
for i in label:
    #print (i[0])
    labelArray.append(i[0])

notPrimeArray2D=[] 
for i in notPrimeArray:
    notPrimeArray2D.append([i])
    
#print (labelArray[0])    

X_train_boost, X_test_boost, y_train_boost, y_test_boost = train_test_split(notPrimeArray2D, labelArray, test_size=0.2, random_state=42)

clf=AdaBoostClassifier(n_estimators=50)

print (len(X_train_boost), len(y_train_boost))

#print (X_train_boost)
#print (y_train_boost)

clf.fit(X_train_boost, y_train_boost)




7999 7999


AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [83]:
def boostpredict(x):
    return(clf.predict(x))

In [84]:
accuracyPrime=0
for i in prime:
    probNotPrime, probPrime= predPrime(i)
    #print('i=', i, '  probNotPrime=', probNotPrime, '  probPrime=', probPrime)
    result=boostpredict(probNotPrime)
    #print('i=', i, '  probNotPrime=', result)
    if result==[1.]:
        accuracyPrime+=1

print(accuracyPrime/len(prime))


0.004882017900732303


In [85]:
#for i in notPrime:
#    probNotPrime, probPrime= predPrime(i)
#    #print('i=', i, '  probNotPrime=', probNotPrime, '  probPrime=', probPrime)
#    print('i=', i, '  probNotPrime=', boostpredict(probNotPrime))
    
    
accuracyNotPrime=0
for i in notPrime:
    probNotPrime, probPrime= predPrime(i)
    #print('i=', i, '  probNotPrime=', probNotPrime, '  probPrime=', probPrime)
    result=boostpredict(probNotPrime)
    #print('i=', i, '  probNotPrime=', result)
    if result==[0.]:
        accuracyNotPrime+=1

print(accuracyNotPrime/len(notPrime))

0.999429874572406


In [330]:
def flatten_list(a, result=None):
    """Flattens a nested list.

        >>> flatten_list([ [1, 2, [3, 4] ], [5, 6], 7])
        [1, 2, 3, 4, 5, 6, 7]
    """
    print(a)
    if result is None:
        result = []

    for x in a:
        if isinstance(x, list):
            flatten_list(x, result)
        else:
            result.append(x)

    return result

a=[ [1, 2, [3, 4] ], [5, 6], 7]
print(flatten_list(a, result=None))

[[1, 2, [3, 4]], [5, 6], 7]
[1, 2, [3, 4]]
[3, 4]
[5, 6]
[1, 2, 3, 4, 5, 6, 7]


In [360]:
print (np.array([num(1, number)]))

[[ 0.  1.  0. ...,  0.  0.  0.]]


In [408]:
print(data)
print (predPrime(2))
probNotPrime, probPrime= predPrime(2)

print (probNotPrime*10)
a= (math.floor(probNotPrime*10))
b=math.floor(probNotPrime*100-a*10)
c=math.floor(probNotPrime*1000-(a*100+b*10))
d=math.floor(probNotPrime*10000-(a*1000+b*100+c*10))
e=math.floor(probNotPrime*100000-d*10)
f=math.floor(probNotPrime*1000000-e*10)
g=math.floor(probNotPrime*10000000-f*10)
h=math.floor(probNotPrime*100000000-g*10)
i=math.floor(probNotPrime*1000000000-h*10)
j=math.floor(probNotPrime*10000000000-i*10)

print ('a=', a)
print ('b=', b)
print ('c=', c)
print ('d=', d)
#print ('e=', e)

#print ('f=', f)
#print ('g=', g)
#print ('h=', h)
#print ('i=', i)
#print ('j=', j)

def digits(x,y):
    result=([math.floor(x*10)])
    if y>0:
        return(result.append(digits(x*10-math.floor(x*10),y-1)))
    else:
        return(result)
    
print (digits(probNotPrime, 1))
#    
#def digitsVect(x):

#for i in data:
    

[[  2.00000000e+00]
 [  3.00000000e+00]
 [  4.00000000e+00]
 ..., 
 [  4.99800000e+03]
 [  4.99900000e+03]
 [  5.00000000e+03]]
(0.84858251, 0.15141749)
8.4858250618
a= 8
b= 4
c= 8
d= 5
None
